package toolchain

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func ReadGeneratedConfig(path string) (map[string]string, error) {
	tools := make(map[string]string)
	file, err := os.Open(path)
	if errors.Is(err, os.ErrNotExist) {
		return tools, nil
	}
	if err != nil {
		return nil, fmt.Errorf("open generated config: %w", err)
	}
	defer file.Close()
	scanner := bufio.NewScanner(file)
	inTools := false
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") {
			if line != "[tools]" {
				return nil, errors.New("generated config contains an unsupported section")
			}
			inTools = true
			continue
		}
		if !inTools {
			return nil, errors.New("generated config contains data outside [tools]")
		}
		key, raw, found := strings.Cut(line, "=")
		key = strings.TrimSpace(key)
		raw = strings.TrimSpace(raw)
		if !found || len(raw) < 2 || raw[0] != '"' || raw[len(raw)-1] != '"' {
			return nil, errors.New("generated config contains an invalid tool entry")
		}
		name, version, err := ValidateRequirement(key, raw[1:len(raw)-1])
		if err != nil || name != key {
			return nil, errors.New("generated config contains a tool outside the safe allowlist")
		}
		tools[name] = version
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("read generated config: %w", err)
	}
	return tools, nil
}

func WriteGeneratedConfig(path string, tools map[string]string) error {
	keys := make([]string, 0, len(tools))
	for tool, version := range tools {
		if _, _, err := ValidateRequirement(tool, version); err != nil {
			return err
		}
		keys = append(keys, tool)
	}
	sort.Strings(keys)
	var contents strings.Builder
	contents.WriteString("# Generated by Commitarium. Runtime-only; never read from the project checkout.\n[tools]\n")
	for _, tool := range keys {
		fmt.Fprintf(&contents, "%s = %q\n", tool, tools[tool])
	}
	return atomicWrite(path, []byte(contents.String()), 0o600)
}

func atomicWrite(path string, contents []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".commitarium-*.tmp")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if err := temporary.Chmod(mode); err != nil {
		temporary.Close()
		return err
	}
	if _, err := temporary.Write(contents); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryPath, path)
}
