package toolchain

import (
	"context"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/EinarLogiOskars/commitarium/internal/project"
)

type projectReaderStub struct {
	stored   project.Project
	overview project.RepositoryOverview
	blobs    map[string][]byte
}

func (reader *projectReaderStub) GetByID(context.Context, string) (project.Project, error) {
	return reader.stored, nil
}

func (reader *projectReaderStub) GetRepositoryOverview(context.Context, string) (project.RepositoryOverview, error) {
	return reader.overview, nil
}

func (reader *projectReaderStub) ReadRepositoryBlob(_ context.Context, _ string, blobID string, _ int64) ([]byte, error) {
	return reader.blobs[blobID], nil
}

func TestManagerConfiguresRuntimeManifestOutsideRepository(t *testing.T) {
	root := t.TempDir()
	reader := &projectReaderStub{stored: project.Project{ID: "prj_test"}}
	manager, err := NewManager(root, reader)
	if err != nil {
		t.Fatalf("create manager: %v", err)
	}
	fixedTime := time.Date(2026, time.September, 15, 12, 0, 0, 0, time.UTC)
	manager.now = func() time.Time { return fixedTime }
	configured, err := manager.Configure(t.Context(), "prj_test", Manifest{
		Source: SourcePicker, Tools: map[string]string{"python": "3.14.7"},
		Services: []string{"postgresql"},
	})
	if err != nil {
		t.Fatalf("configure manifest: %v", err)
	}
	if configured.Status != StatusConfigured || configured.UpdatedAt != fixedTime {
		t.Fatalf("unexpected configured manifest %+v", configured)
	}
	configPath := filepath.Join(root, "projects", "prj_test", "mise.toml")
	contents, err := os.ReadFile(configPath)
	if err != nil || string(contents) != "# Generated by Commitarium. Runtime-only; never read from the project checkout.\n[tools]\npython = \"3.14.7\"\n" {
		t.Fatalf("unexpected generated config %q err=%v", contents, err)
	}
	loaded, err := manager.Get(t.Context(), "prj_test")
	if err != nil || loaded.Tools["python"] != "3.14.7" || loaded.Services[0] != "postgresql" || loaded.ServicesRunnable {
		t.Fatalf("loaded manifest=%+v err=%v", loaded, err)
	}
	if err := WriteGeneratedConfig(configPath, map[string]string{"python": "3.14.7", "go": "1.27.1"}); err != nil {
		t.Fatalf("simulate runtime requirement: %v", err)
	}
	loaded, err = manager.Get(t.Context(), "prj_test")
	if err != nil || loaded.Tools["go"] != "1.27.1" {
		t.Fatalf("runtime-added tool was not reflected: manifest=%+v err=%v", loaded, err)
	}
}

func TestManagerReadsRuntimeConfigWithoutManifest(t *testing.T) {
	root := t.TempDir()
	reader := &projectReaderStub{stored: project.Project{ID: "prj_test"}}
	manager, err := NewManager(root, reader)
	if err != nil {
		t.Fatalf("create manager: %v", err)
	}
	if err := WriteGeneratedConfig(filepath.Join(root, "projects", "prj_test", "mise.toml"),
		map[string]string{"rust": "1.98.1"}); err != nil {
		t.Fatalf("write runtime config: %v", err)
	}
	loaded, err := manager.Get(t.Context(), "prj_test")
	if err != nil || loaded.Source != SourceRuntime || loaded.Tools["rust"] != "1.98.1" {
		t.Fatalf("runtime manifest=%+v err=%v", loaded, err)
	}
}

func TestManagerDetectsExactRepositoryToolsWithoutExecutingConfig(t *testing.T) {
	reader := &projectReaderStub{
		stored: project.Project{ID: "prj_test"},
		overview: project.RepositoryOverview{Tree: []project.RepositoryTreeEntry{
			{Path: "pyproject.toml", Type: "file", BlobID: "python", Size: 10},
			{Path: "mise.toml", Type: "file", BlobID: "mise", Size: 100},
		}},
		blobs: map[string][]byte{"mise": []byte("[tools]\npython = \"3.13.7\"\nnode = \"24.21.0\"\n[env]\nSECRET = \"must-not-run\"\n[tasks.bad]\nrun = \"false\"\n")},
	}
	manager, err := NewManager(t.TempDir(), reader)
	if err != nil {
		t.Fatalf("create manager: %v", err)
	}
	suggestion, err := manager.Detect(t.Context(), "prj_test")
	if err != nil {
		t.Fatalf("detect toolchain: %v", err)
	}
	if suggestion.Confidence != "high" || suggestion.Tools["python"] != "3.13.7" ||
		suggestion.Tools["node"] != "24.21.0" {
		t.Fatalf("unexpected suggestion %+v", suggestion)
	}
}

func TestManifestRejectsFloatingOrUnknownTools(t *testing.T) {
	for _, manifest := range []Manifest{
		{Source: SourcePicker, Tools: map[string]string{"python": "latest"}},
		{Source: SourcePicker, Tools: map[string]string{"terraform": "1.0.0"}},
		{Source: SourcePicker, Tools: map[string]string{"python": "3.14.7"}, Services: []string{"postgres; bad"}},
	} {
		if _, err := NormalizeManifest(manifest); err == nil {
			t.Fatalf("expected invalid manifest %+v", manifest)
		}
	}
}
