package toolchain

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"syscall"
	"testing"
	"time"

	"github.com/EinarLogiOskars/commitarium/internal/project"
)

type projectReaderStub struct {
	stored          project.Project
	overview        project.RepositoryOverview
	evidence        project.RepositoryToolchainEvidence
	blobs           map[string][]byte
	deletionPending bool
}

func (reader *projectReaderStub) GetByID(context.Context, string) (project.Project, error) {
	return reader.stored, nil
}

func (reader *projectReaderStub) GetRepositoryOverview(context.Context, string) (project.RepositoryOverview, error) {
	return reader.overview, nil
}

func (reader *projectReaderStub) ReadRepositoryBlob(_ context.Context, _ string, blobID string, _ int64) ([]byte, error) {
	return reader.blobs[blobID], nil
}

func (reader *projectReaderStub) GetRepositoryToolchainEvidence(context.Context, string) (project.RepositoryToolchainEvidence, error) {
	return reader.evidence, nil
}

func (reader *projectReaderStub) ProjectDeletionPending(context.Context, string) (bool, error) {
	return reader.deletionPending, nil
}

func TestManagerDoesNotConfigureProjectWithPendingDeletion(t *testing.T) {
	root := t.TempDir()
	reader := &projectReaderStub{
		stored: project.Project{ID: "prj_test"}, deletionPending: true,
	}
	manager, err := NewManager(root, reader)
	if err != nil {
		t.Fatalf("create manager: %v", err)
	}
	_, err = manager.Configure(t.Context(), "prj_test", Manifest{
		Source: SourcePicker, Tools: map[string]string{"python": "3.14.7"},
	})
	if !errors.Is(err, project.ErrNotFound) {
		t.Fatalf("configure deleting project error=%v", err)
	}
	if _, err := os.Stat(filepath.Join(root, "projects", "prj_test")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("deleting project gained toolchain artifacts: %v", err)
	}
}

func TestManagerConfiguresRuntimeManifestOutsideRepository(t *testing.T) {
	root := t.TempDir()
	reader := &projectReaderStub{stored: project.Project{ID: "prj_test"}}
	manager, err := NewManager(root, reader)
	if err != nil {
		t.Fatalf("create manager: %v", err)
	}
	fixedTime := time.Date(2026, time.September, 15, 12, 0, 0, 0, time.UTC)
	manager.now = func() time.Time { return fixedTime }
	configured, err := manager.Configure(t.Context(), "prj_test", Manifest{
		Source: SourcePicker, Tools: map[string]string{"python": "3.14.7"},
		Services: []string{"postgresql"},
	})
	if err != nil {
		t.Fatalf("configure manifest: %v", err)
	}
	if configured.Status != StatusConfigured || configured.UpdatedAt != fixedTime ||
		configured.ProvisioningStatus != ProvisioningPending {
		t.Fatalf("unexpected configured manifest %+v", configured)
	}
	configPath := filepath.Join(root, "projects", "prj_test", "mise.toml")
	contents, err := os.ReadFile(configPath)
	if err != nil || string(contents) != "# Generated by Commitarium. Runtime-only; never read from the project checkout.\n[tools]\npython = \"3.14.7\"\n" {
		t.Fatalf("unexpected generated config %q err=%v", contents, err)
	}
	loaded, err := manager.Get(t.Context(), "prj_test")
	if err != nil || loaded.Tools["python"] != "3.14.7" || loaded.Services[0] != "postgresql" ||
		loaded.ServicesRunnable || loaded.ProvisioningStatus != ProvisioningPending {
		t.Fatalf("loaded manifest=%+v err=%v", loaded, err)
	}
	if err := WriteGeneratedConfig(configPath, map[string]string{"python": "3.14.7", "go": "1.27.1"}); err != nil {
		t.Fatalf("simulate runtime requirement: %v", err)
	}
	loaded, err = manager.Get(t.Context(), "prj_test")
	if err != nil || loaded.Tools["go"] != "1.27.1" {
		t.Fatalf("runtime-added tool was not reflected: manifest=%+v err=%v", loaded, err)
	}
}

func TestManagerReadsRuntimeConfigWithoutManifest(t *testing.T) {
	root := t.TempDir()
	reader := &projectReaderStub{stored: project.Project{ID: "prj_test"}}
	manager, err := NewManager(root, reader)
	if err != nil {
		t.Fatalf("create manager: %v", err)
	}
	if err := WriteGeneratedConfig(filepath.Join(root, "projects", "prj_test", "mise.toml"),
		map[string]string{"rust": "1.98.1"}); err != nil {
		t.Fatalf("write runtime config: %v", err)
	}
	loaded, err := manager.Get(t.Context(), "prj_test")
	if err != nil || loaded.Source != SourceRuntime || loaded.Tools["rust"] != "1.98.1" {
		t.Fatalf("runtime manifest=%+v err=%v", loaded, err)
	}
}

func TestManagerReadsInstallingStateWithoutWaitingForInstallLock(t *testing.T) {
	root := t.TempDir()
	reader := &projectReaderStub{stored: project.Project{ID: "prj_test"}}
	manager, err := NewManager(root, reader)
	if err != nil {
		t.Fatalf("create manager: %v", err)
	}
	if _, err := manager.Configure(t.Context(), "prj_test", Manifest{
		Source: SourcePicker, Tools: map[string]string{"python": "3.14.7"},
	}); err != nil {
		t.Fatalf("configure manifest: %v", err)
	}
	configPath := filepath.Join(root, "projects", "prj_test", "mise.toml")
	lock, err := os.OpenFile(configPath+".lock", os.O_CREATE|os.O_RDWR, 0o600)
	if err != nil {
		t.Fatalf("open install lock: %v", err)
	}
	defer lock.Close()
	if err := syscall.Flock(int(lock.Fd()), syscall.LOCK_EX); err != nil {
		t.Fatalf("hold install lock: %v", err)
	}
	defer syscall.Flock(int(lock.Fd()), syscall.LOCK_UN)
	if err := WriteProvisioningState(configPath, ProvisioningState{Status: ProvisioningInstalling}); err != nil {
		t.Fatalf("write installing state: %v", err)
	}

	loaded, err := manager.Get(t.Context(), "prj_test")
	if err != nil || loaded.ProvisioningStatus != ProvisioningInstalling {
		t.Fatalf("loaded manifest=%+v err=%v", loaded, err)
	}
}

func TestManagerDetectsExactRepositoryToolsWithoutExecutingConfig(t *testing.T) {
	reader := &projectReaderStub{
		stored: project.Project{ID: "prj_test"},
		overview: project.RepositoryOverview{Tree: []project.RepositoryTreeEntry{
			{Path: "pyproject.toml", Type: "file", BlobID: "python", Size: 10},
			{Path: "pom.xml", Type: "file", BlobID: "maven", Size: 10},
			{Path: "mise.toml", Type: "file", BlobID: "mise", Size: 100},
		}},
		blobs: map[string][]byte{"mise": []byte("[tools]\npython = \"3.13.7\"\nnode = \"24.21.0\"\n[env]\nSECRET = \"must-not-run\"\n[tasks.bad]\nrun = \"false\"\n")},
	}
	manager, err := NewManager(t.TempDir(), reader)
	if err != nil {
		t.Fatalf("create manager: %v", err)
	}
	suggestion, err := manager.Detect(t.Context(), "prj_test")
	if err != nil {
		t.Fatalf("detect toolchain: %v", err)
	}
	if suggestion.Confidence != "high" || suggestion.Tools["python"] != "3.13.7" ||
		suggestion.Tools["node"] != "24.21.0" ||
		suggestion.Tools["java"] != "temurin-21.0.12+8.0.LTS" ||
		suggestion.Tools["maven"] != "3.9.16" {
		t.Fatalf("unexpected suggestion %+v", suggestion)
	}
}

func TestManifestRejectsFloatingOrUnknownTools(t *testing.T) {
	for _, manifest := range []Manifest{
		{Source: SourcePicker, Tools: map[string]string{"python": "latest"}},
		{Source: SourcePicker, Tools: map[string]string{"terraform": "1.0.0"}},
		{Source: SourcePicker, Tools: map[string]string{"python": "3.14.7"}, Services: []string{"postgres; bad"}},
	} {
		if _, err := NormalizeManifest(manifest); err == nil {
			t.Fatalf("expected invalid manifest %+v", manifest)
		}
	}
}

func TestDeleteProjectRemovesOnlyPerProjectFilesAndKeepsSharedCache(t *testing.T) {
	root := t.TempDir()
	reader := &projectReaderStub{stored: project.Project{ID: "prj_one", Name: "One"}}
	manager, err := NewManager(root, reader)
	if err != nil {
		t.Fatalf("create manager: %v", err)
	}
	if _, err := manager.Configure(t.Context(), "prj_one", Manifest{
		Source: SourcePicker, Tools: map[string]string{"python": "3.14.7"}, Services: []string{},
	}); err != nil {
		t.Fatalf("configure first project: %v", err)
	}
	reader.stored = project.Project{ID: "prj_two", Name: "Two"}
	if _, err := manager.Configure(t.Context(), "prj_two", Manifest{
		Source: SourcePicker, Tools: map[string]string{"node": "24.21.0"}, Services: []string{},
	}); err != nil {
		t.Fatalf("configure second project: %v", err)
	}
	if err := os.MkdirAll(filepath.Join(root, "cache"), 0o700); err != nil {
		t.Fatalf("create shared cache: %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, "cache", "shared"), []byte("keep"), 0o600); err != nil {
		t.Fatalf("write shared cache marker: %v", err)
	}
	if err := manager.DeleteProject(t.Context(), "prj_one"); err != nil {
		t.Fatalf("delete project toolchain: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, "projects", "prj_one")); !errors.Is(err, os.ErrNotExist) {
		t.Fatalf("deleted project directory remains: %v", err)
	}
	for _, path := range []string{
		filepath.Join(root, "projects", "prj_two", "manifest.json"),
		filepath.Join(root, "cache", "shared"),
	} {
		if _, err := os.Stat(path); err != nil {
			t.Fatalf("unrelated/shared file %s was removed: %v", path, err)
		}
	}
	if err := manager.DeleteProject(t.Context(), "prj_one"); err != nil {
		t.Fatalf("idempotent toolchain delete: %v", err)
	}
}
